name: Good CI/CD Pipeline with Doppler Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doppler CLI
        run: |
          curl -Ls https://cli.doppler.com/install.sh | sh

      - name: Configure Doppler
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          doppler setup --project ci-cd-lab --config development --token $DOPPLER_TOKEN

      - name: Fetch Secrets from Doppler
        run: |
          doppler run -- printenv | grep SECRET_KEY

      - name: Build and Deploy
        run: |
          echo "Building application..."
          echo "Deploying application..."
          echo "Using SECRET_KEY=$(doppler secrets get SECRET_KEY --plain)"