name: Good CI/CD Pipeline with Doppler Web (Docker)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Secrets with Doppler (Docker)
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          docker run --rm -e DOPPLER_TOKEN=${DOPPLER_TOKEN} dopplerhq/cli:latest secrets download --format env --no-file

      - name: Build and Deploy
        run: |
          echo "Building application..."
          echo "Deploying application..."